// user
export const LOGIN = "login"
export const LOGOUT = "logout"
export const LOGIN_SUCCEEDED = "login_successed"
export const LOGIN_FAILED = "login_failed"
export const GET_USER_INFO = "get_user_info"
export const GET_USER_INFO_BY_ID = "get_user_info_by_id"
export const GET_USER_INFO_BY_ID_SUCCESSED = "get_user_info_by_id_successed"
export const GET_USER_INFO_BY_ID_FAILED = "get_user_info_by_id_failed"
export const GET_USER_LISTS = "get_user_lists"
export const DELETE_USER = "delete_user"
export const ADD_USER = "add_user"
export const UPDATE_USER = "update_user"
export const CHANGE_STEP = "change_step"
export const SEND_UPDATE_PASSWORD_EMAIL = "send_update_password_email"
export const SEND_UPDATE_PASSWORD_EMAIL_SUCCESSED = "send_update_password_email_successed"
export const SEND_UPDATE_PASSWORD_EMAIL_FAILED = "send_update_password_email_failed"
export const VERIFY_UPDATE_PASSWORD_CODE = "verify_update_password_code"
export const CHANGE_PASSWORD = "change_password"
export const CHANGE_PASSWORD_BY_OLD_PASSWORD = "change_password_by_old_password"
export const GET_USER_LISTS_SUCCESSED = "get_user_lists_successed"
export const GET_USER_LISTS_FAILED = "get_user_lists_failed"
export const CHANGE_USER_STATUS = "change_user_status"

// menu
export const CHANGE_PATH = "change_path"
export const CHANGE_COLLAPSED = "change_collapsed"

// setting
export const GET_SETTING_LISTS = "get_setting_lists"
export const GET_SETTING_LISTS_SUCCESSED = "get_setting_lists_successed"
export const GET_SETTING_LISTS_FAILED = "get_setting_list_failed"
export const ADD_SETTING = "add_setting"
export const UPDATE_SETTING = "update_setting"
export const DELETE_SETTING = "delete_setting"

// material category
export const GET_MATERIAL_CATEGORY_LISTS = "get_material_category_lists"
export const GET_MATERIAL_CATEGORY_LISTS_SUCCESSED = "get_material_category_lists_successed"
export const GET_MATERIAL_CATEGORY_LISTS_FAILED = "get_material_category_lists_failed"
export const GET_ALL_MATERIAL_CATEGORY_LISTS = "get_all_material_category_lists"
export const GET_ALL_MATERIAL_CATEGORY_LISTS_SUCCESSED = "get_all_material_category_lists_successed"
export const GET_ALL_MATERIAL_CATEGORY_LISTS_FAILED = "get_all_material_category_lists_failed"
export const ADD_MATERIAL_CATEGORY = "add_material_category"
export const UPDATE_MATERIAL_CATEGORY = "update_material_category"
export const DELETE_MATERIAL_CATEGORY = "delete_material_category"

// material
export const GET_MATERIAL_LISTS = "get_material_lists"
export const GET_MATERIAL_LISTS_SUCCESSED = "get_material_lists_successed"
export const GET_MATERIAL_LISTS_FAILED = "get_material_list_failed"
export const ADD_MATERIAL = "add_material"
export const DELETE_MATERIAL = "delete_material"
export const UPDATE_MATERIAL = "update_material"

// article category
export const GET_ARTICLE_CATEGORY_LISTS = "get_article_category_lists"
export const GET_ARTICLE_CATEGORY_LISTS_SUCCESSED = "get_article_category_lists_successed"
export const GET_ARTICLE_CATEGORY_LISTS_FAILED = "get_article_category_list_failed"
export const GET_ALL_ARTICLE_CATEGORY_LISTS = "get_all_article_category_lists"
export const GET_ALL_ARTICLE_CATEGORY_LISTS_SUCCESSED = "get_all_article_category_lists_successed"
export const GET_ALL_ARTICLE_CATEGORY_LISTS_FAILED = "get_all_article_category_list_failed"
export const GET_ARTICLE_CATEGORY = "get_article_category"
export const GET_ARTICLE_CATEGORY_SUCCESSED = "get_article_category_successed"
export const GET_ARTICLE_CATEGORY_FAILED = "get_article_category_failed"
export const ADD_ARTICLE_CATEGORY = "add_article_category"
export const UPDATE_ARTICLE_CATEGORY = "update_article_category"
export const DELETE_ARTICLE_CATEGORY = "delete_article_category"
export const CHANGE_ARTICLE_CATEGORY_STATUS = "change_article_category_status"

// article
export const GET_ARTICLE_LISTS = "get_article_lists"
export const GET_ARTICLE_LISTS_SUCCESSED = "get_article_lists_successed"
export const GET_ARTICLE_LISTS_FAILED = "get_article_lists_failed"
export const GET_ARTICLE = "get_article"
export const GET_ARTICLE_SUCCESSED = "get_article_successed"
export const GET_ARTICLE_FAILED = "get_article_failed"
export const ADD_ARTICLE = "add_article"
export const UPDATE_ARTICLE = "update_article"
export const DELETE_ARTICLE = "delete_article"
export const CHANGE_ARTICLE_STATUS = "change_article_status"

